[package]
name = "ferrite"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fe"
path = "src/main.rs"

[dependencies]
crossterm = "0.23"
shellexpand = "2.1"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
